CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
tipo VARCHAR(10) NOT NULL
);
GO

CREATE TABLE ESTILO(
idEstilo TINYINT PRIMARY KEY IDENTITY(1,1),
tipoEstilo VARCHAR(15) NOT NULL
);
GO

CREATE TABLE USUARIO(
idUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
email CHAR(256) NOT NULL,
nome VARCHAR(60) NOT NULL,
senha VARCHAR (20) NOT NULL
);
GO

CREATE TABLE ALBUM(
idAlbum TINYINT PRIMARY KEY IDENTITY(1,1),
idUsuario TINYINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
idEstilo TINYINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
artista VARCHAR(20) NOT NULL,
dataLancamento DATE NOT NULL
);
GO