USE EMPRESA;
GO

SELECT * FROM PESSOA
SELECT * FROM TELEFONE
SELECT * FROM EMAIL
SELECT * FROM CNH

SELECT nomePessoa, numeroTelefone, idCNH, end_Email FROM PESSOA
LEFT JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idPessoa
FULL OUTER JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idPessoa
ORDER BY nomePessoa DESC
GO