CREATE DATABASE PCLINICS;
GO 

USE PCLINICS;
GO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
nomeClinica VARCHAR(30) NOT NULL
);
GO

CREATE TABLE DONO(
idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeDono VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TIPOPET(
idTipoPet SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEspecie VARCHAR(20) NOT NULL
);
GO

CREATE TABLE RACA(
idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
idTipoPet SMALLINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
nomeRaca VARCHAR(20) NOT NULL
);
GO

CREATE TABLE PET(
idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
idRaca SMALLINT FOREIGN KEY REFERENCES RACA(idRaca),
idDono SMALLINT FOREIGN KEY REFERENCES DONO(idDono),
nomePet VARCHAR(15) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVet SMALLINT PRIMARY KEY IDENTITY(1,1),
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
nomeVeterinario VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO(
idAtendimento SMALLINT PRIMARY KEY IDENTITY(1,1),
idVet SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVet),
idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
dataAtendimento DATE NOT NULL
);
GO

